version: "3.8"

services:
  db:
    container_name: "test-mysql"
    image:  mysql:8.0.23
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "mysecretpw"
      MYSQL_DATABASE: "crud-memo"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "mysecretpw"
    volumes:
      - mysql_data:/var/lib/mysql  
    command:  --default-authentication-plugin=mysql_native_password
  api:
    container_name: "test-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - db
    volumes:
      - .:/app/ 

networks:
  default:
volumes:
  mysql_data:        